### ISSUE TITLE
Expose authenticate and checkRole functions

### ISSUE THREAD

**Issue by tomyitav** [graphql-community/graphql-directive-auth#19]
Hi, thanks for creating this awesome project!
I have a case where I want to slightly extend the default authenticate function. I basically want to check a simple condition (skipAuth) and if not- to delegate to the default authenticate function. (Of course I can override the function completely, but that would be verbose code duplication). Can you expose the two default functions in index.ts file, for enabling this delegation?
Thanks!

**Comment by czystyl** [comment]
Hi @tomyitav, firstly I want to say that I'm glad that you are using this directive. 

Regarding the export - it's a good idea, and it should be exported for sure. Do you want to make PR and do this? ;) otherwise, I'll do it later this weekend :)

**Comment by tomyitav** [comment]
Hi @czystyl, I have opened a PR. Let me know if it's OK and you can publish a new version.
Thanks!

**Comment by czystyl** [comment]
``` graphql-directive-auth 0.3.0 published 🎉``` Thanks for your help :)
