### ISSUE TITLE
Multiple roles in JWT

### ISSUE THREAD

**Issue by dragonfriend0013** [graphql-community/graphql-directive-auth#22]
I have been looking at the code and it appears that it will not support multiple roles in the JWT.  for example, a user who has the role of USER as well as the role of ADMIN.  Can this be updated so that the JWT claim could be a string, or an array?
role: 'USER'
role: ['USER','ADMIN']

**Comment by czystyl** [comment]
Hi, you can use it like this: ```@hasRole(role: "ADMIN, MANAGER, OWNER, USER")```

**Comment by czystyl** [comment]
So for that case, you can implement your own function for checking the roles and pass it to the config of the directive.

Here: https://github.com/graphql-community/graphql-directive-auth/blob/master/src/utils.ts#L37-L54 is the default function for checking roles. You can copy and modify this function and then pass to the config here: https://github.com/graphql-community/graphql-directive-auth/blob/master/example/schema.ts#L42

```
const customAuth = AuthDirectives({
  checkRoleFunc: yourCustomFunction
});
```

**Comment by kevinlabory** [comment]
If you're looking for an implementation of this custom function here is an example : 

```
import { AuthenticationError } from 'apollo-server';
import jwt from 'jsonwebtoken';
import { jwtSecret } from '../config';

/**
 * checkRoleCustomFunc resolver
 *
 * @param  {Object} ctx
 * @param  {Object} value
 */
export default (ctx: Object, value: string) => {
  const authorization =
    ctx.request && ctx.request.headers && ctx.request.headers.authorization;

  if (!authorization) {
    throw new AuthenticationError(Invalid token!');
  }

  const token = authorization.replace('Bearer ', '');

  const decodedToken = jwt.verify(token, jwtSecret);

  const mandatoryRoles = value.split(',');

  if (decodedToken && decodedToken.user && decodedToken.user.roles) {
    const { roles } = decodedToken.user;
    const rolesIntersection = roles.filter((role) =>
      mandatoryRoles.includes(role),
    );

    if (rolesIntersection.length === 0) {
      throw new AuthenticationError('Invalid role!');
    }

    return rolesIntersection;
  }

  throw new AuthenticationError('Unauthorized access!');
};
```

**Comment by czystyl** [comment]
Thanks @kevinlabory - Could you add your examples to the README.md?

**Comment by kevinlabory** [comment]
@czystyl Done
